### ISSUE TITLE
[Melee] GmTtAll Exception

### ISSUE THREAD

**Issue by PsiLupan** [Ploaj/StudioSB#11]
Attempting to open the file crashes with the following exception and stack trace.

```************** Exception Text **************
System.InvalidCastException: Unable to cast object of type 'HSDLib.Common.HSD_MOBJ' to type 'HSDLib.Common.HSD_Image'.
   at HSDLib.HSDReader.ReadObject[T](UInt32 Offset, T Type)
   at System.Dynamic.UpdateDelegates.UpdateAndExecute3[T0,T1,T2,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   at CallSite.Target(Closure , CallSite , HSDReader , UInt32 , Object )
   at HSDLib.IHSDNode.Open(HSDReader Reader)
   at HSDLib.HSDReader.ReadObject[T](UInt32 Offset, T Type)
   at System.Dynamic.UpdateDelegates.UpdateAndExecute3[T0,T1,T2,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   at CallSite.Target(Closure , CallSite , HSDReader , UInt32 , Object )
   at HSDLib.IHSDNode.Open(HSDReader Reader)
   at HSDLib.HSDReader.ReadObject[T](UInt32 Offset, T Type)
   at System.Dynamic.UpdateDelegates.UpdateAndExecute3[T0,T1,T2,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   at CallSite.Target(Closure , CallSite , HSDReader , UInt32 , Object )
   at HSDLib.IHSDNode.Open(HSDReader Reader)
   at HSDLib.HSDReader.ReadObject[T](UInt32 Offset, T Type)
   at System.Dynamic.UpdateDelegates.UpdateAndExecute3[T0,T1,T2,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   at CallSite.Target(Closure , CallSite , HSDReader , UInt32 , Object )
   at HSDLib.IHSDNode.Open(HSDReader Reader)
   at HSDLib.Common.HSD_JOBJ.Open(HSDReader Reader)
   at HSDLib.HSDReader.ReadObject[T](UInt32 Offset, T Type)
   at HSDLib.IHSDNode.Open(HSDReader Reader)
   at HSDLib.Common.HSD_JOBJ.Open(HSDReader Reader)
   at HSDLib.HSDReader.ReadObject[T](UInt32 Offset, T Type)
   at HSDLib.HSDReader.ReadObject[T](UInt32 Offset)
   at HSDLib.HSDRoot.Open(HSDReader Reader)
   at HSDLib.HSDFile.Decompile(Stream stream)
   at StudioSB.Scenes.Melee.HSDScene.LoadFromFile(String FileName)
   at StudioSB.MainForm.OpenFile(String FilePath)
   at StudioSB.MainForm.OpenFile(Object sender, EventArgs args)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

**Comment by Ploaj** [comment]
StudioSB is only for model files (Pl**** and Ty*)

This "HSDRawViewer" here can open any of the dats: 
https://github.com/Ploaj/HSDLib
