### ISSUE TITLE
Maya FBX (Partially) Not Supported

### ISSUE THREAD

**Issue by ThatNintendoNerd** [Ploaj/StudioSB#21]
Sometimes when trying to import an [.fbx](https://cdn.discordapp.com/attachments/220619973465210880/655962236329656339/plane.fbx) file from Maya results in the following exception:
```
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at StudioSB.IO.Formats.IO_FBX.CreateVertex(Matrix4 transform, FbxGeometry geometry, Int32 Index, Vector4[] boneIndices, Vector4[] boneWeights, Single scale)
   at StudioSB.IO.Formats.IO_FBX.ImportIOModel(String FileName)
   at StudioSB.MainForm.LoadScene(String filePath, SBScene loadedScene)
   at StudioSB.MainForm.ImportToScene(Object sender, EventArgs args)
```
In my experience, it only happens with plane models. However I've worked with more complex geometry and sometimes the same error is brought up.

**Comment by Super4ng** [comment]
![Screenshot_20191215-204906_Discord](https://user-images.githubusercontent.com/50799782/70875725-938b3100-1f7c-11ea-8d4c-3da03c958438.jpg)
![Screenshot_20191215-204921_Discord](https://user-images.githubusercontent.com/50799782/70875729-97b74e80-1f7c-11ea-952f-dfc53976d9aa.jpg)

I believe I had something similar, but I'm guessing he has patched it since then?

**Comment by Ploaj** [comment]
This may be fixed now.
